version: "2"
services:
  rekber-wapuppet-node:
    container_name: "rekber-wapuppet-node"
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "9002:3000"
    networks:
      rekber-net:

networks:
  rekber-net:
    external: true