version: "2"
services:
  rekber-wapuppet-node:
    container_name: "rekber-wapuppet-node"
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: always
    volumes:
      - .:/var/www
      - /var/www/node_modules
    ports:
      - "9002:8989"
    networks:
      rekber-net:

networks:
  rekber-net:
    external: true