version: "2"
services:
  rekber-wapuppet-node:
    container_name: "rekber-wapuppet-node"
    build:
      context: .
      dockerfile: ./Dockerfile
    command: ["npm install", "&&", "npm run start"]
    expose:
      - 8989
    volumes:
      - ".:/var/www"
    ports:
      - "9002:8989"
    networks:
      rekber-net:

networks:
  rekber-net:
    external: true